language: php
php:
- 7.1
dist: trusty
services:
- mysql
addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server
before_install:
- openssl aes-256-cbc -K $encrypted_accc6ed069c3_key -iv $encrypted_accc6ed069c3_iv
  -in scripts/deploy_rsa.enc -out /tmp/deploy_rsa -d
- mysql -e 'CREATE DATABASE IF NOT EXISTS howzit;'
- composer self-update
- composer validate --no-check-all --ansi
- composer install -n
- cp .env.example .env
- php artisan migrate
- php artisan db:seed
- vendor/bin/phpunit --coverage-clover=coverage.xml
script: 
after_success:
- bash <(curl -s https://codecov.io/bash)
- rm .env
- echo "Unicorn Time"
deploy:
- provider: script
  script: "./scripts/travis.sh"
  skip_cleanup: true
  on:
    branch: deploy-travis
- provider: script
  script: "./scripts/travis.sh"
  skip_cleanup: true
  on:
    branch: dev
- provider: script
  script: "./scripts/travis.sh"
  skip_cleanup: true
  on:
    branch: master
