language: php
php:
- 7.1
dist: trusty
services:
- mysql
addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS howzit;'
- composer self-update
- composer validate --no-check-all --ansi
- composer install -n
- cp .env.example .env
- php artisan migrate
- php artisan db:seed
- vendor/bin/phpunit --coverage-clover=coverage.xml
script:
#- openssl aes-256-cbc -K $encrypted_f14979ee4dd2_key -iv $encrypted_f14979ee4dd2_iv
#  -in scripts/deploy_rsa.enc -out /tmp/deploy_rsa -d
#- eval "$(ssh-agent -s)"
#- chmod 600 /tmp/deploy_rsa
#- ssh-add /tmp/deploy_rsa
after_success:
- bash <(curl -s https://codecov.io/bash)
- rm .env
- echo "Unicorn Time"
deploy:
- provider: script
  script: "./scripts/travis.sh"
  skip_cleanup: true
  on:
    branch: dev
- provider: script
  script: "./scripts/travis.sh"
  skip_cleanup: true
  on:
    branch: master
